[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  # Configuración global para todas las functions
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "canvas"]

[functions."registrar-trabajador"]
  # Timeout extendido para móviles (hasta 10 segundos)
  timeout = 10
  # Memoria aumentada para procesamiento de archivos
  memory = 1024

[functions."register-worker"]
  # Timeout extendido para móviles (hasta 10 segundos)
  timeout = 10
  # Memoria aumentada para procesamiento de archivos
  memory = 1024

[functions."worker-documents"]
  # Timeout para consultas
  timeout = 5
  memory = 512

# Headers específicos para CORS y móviles
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Content-Length, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"
    # Límites específicos para archivos móviles
    Access-Control-Expose-Headers = "Content-Length, Content-Range"

# Configuración específica para manejo de archivos grandes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  
  # Headers específicos para upload de archivos
  [redirects.headers]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración de límites para móviles
[dev]
  functions = "netlify/functions"
  functionsPort = 8888
  # Aumentar timeout en desarrollo
  functionsTimeout = 30

# Variables de entorno para optimización móvil
[context.production.environment]
  NODE_ENV = "production"
  MOBILE_OPTIMIZATION = "true"
  MAX_FILE_SIZE = "50000000"  # 50MB
  
[context.deploy-preview.environment]
  NODE_ENV = "development"
  MOBILE_OPTIMIZATION = "true"